version: '2'

services:
    teamcity:
        image: jetbrains/teamcity-server:2017.2.4
        volumes:
            - ./data/server/datadir:/data/teamcity_server/datadir
            - ./data/server/logs:/opt/teamcity/logs
        ports:
            - 8111:8111
    teamcity-agent:
        image: jetbrains/teamcity-agent:2017.2.4
        volumes:
            - ./data/agent:/data/teamcity_agent/conf
        environment:
          - SERVER_URL=http://teamcity:8111
          - AGENT_NAME=full-agent
          - DOCKER_IN_DOCKER=start
        privileged: true
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:6.1.0
        container_name: artifactory
        ports:
          - 8081:8081
        volumes:
          - /data/artifactory:/var/opt/jfrog/artifactory
#        Add extra Java options by uncommenting the following lines
#        environment:
#         - EXTRA_JAVA_OPTIONS=-Xmx4g
        restart: always
        ulimits:
          nproc: 65535
          nofile:
            soft: 32000
            hard: 40000